stages:
    - build
    - tests
    - code-analysis
    - push
    - deploy

include:
  - project: 'IUT_INF63/generic-ci'
    ref: 'main'
    file:
      - 'build/.documentation-build.yml'
      - 'deploy/.docker-deploy.yml'

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd src/
    - dotnet restore Jinx_SansMaui.slnx
    - dotnet build Jinx_SansMaui.slnx -c Release --no-restore

build-maui:
  stage: build
  image: codefirst.iut.uca.fr/macheval/codefirstimages/maui10:amd64
  script:
    - cd src/
    - rm -f JinxApp/JinxApp.csproj.user
    - dotnet build JinxApp/JinxApp.csproj -c Release /p:TargetFramework=net10.0-android /p:TreatWarningsAsErrors=false
    - dotnet publish JinxApp/JinxApp.csproj -c Release /p:TargetFramework=net10.0-android --no-restore -o $CI_PROJECT_DIR/build/release /p:TreatWarningsAsErrors=false
  rules:
    - when: manual

tests:
  stage: tests
  image: mcr.microsoft.com/dotnet/sdk:10.0
  script:
    - cd src/
    - dotnet restore Tests/Models.Tests/Models.Tests.csproj
    - dotnet restore Tests/Managers.Tests/Managers.Tests.csproj
    - dotnet test Tests/Models.Tests/Models.Tests.csproj -c Release
    - dotnet test Tests/Managers.Tests/Managers.Tests.csproj -c Release
  needs:
    - job: build

sonar_analysis:
  stage: code-analysis
  image: codefirst.iut.uca.fr/macheval/codefirstimages/dotnet10:main
  variables:
    SONAR_PROJECT_KEY: CI_Jinx
  script:
    - cd src/
    - dotnet restore Jinx_SansMaui.slnx
    - dotnet sonarscanner begin /k:$SONAR_PROJECT_KEY /d:sonar.host.url=$SONAR_HOST /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.coverage.exclusions="Tests/**" /d:sonar.login=$SONAR_TOKEN
    - dotnet build Jinx_SansMaui.slnx -c Release --no-restore
    - dotnet test Tests/Models.Tests/Models.Tests.csproj --logger trx --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
    - dotnet test Tests/Managers.Tests/Managers.Tests.csproj --logger trx --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
    - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
    - echo "Line coverage :" $(grep -oPi 'line-rate="\K[^"]+' **/coverage.cobertura.xml | head -n 1 | awk '{print $1*100"%"}')
    - dotnet publish ConsoleApp/ConsoleApp.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release
    - dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
  needs:
    - job: tests
  coverage: '/Line coverage\s*:\s*(\d+(?:\.\d+)?%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/coveragereport/SonarQube.xml

build-doxygen-documentation:
  extends: .build-documentation
  stage: build
  variables:
    DOXYGEN_FOLDER_PATH: docs/doxygen
    DOC_TYPE: DOXYGEN
    DESTINATION_REGISTRY_IMAGE_NAME: codefirst.iut.uca.fr/iut_inf63/2026_1a_g12_maui/2026_1a_g2_poulain_boudon/doxygen
    DESTINATION_REGISTRY_IMAGE_VERSION: main
  needs:
    - job: build
  when: manual

push-doxygen-documentation:
  extends: .push-documentation-image
  stage: push
  needs:
    - build-doxygen-documentation

deploy-my-pod:
  extends: .deploy-image
  stage: deploy
  variables:
      CONTAINER_NAME: jinxdoc
      CONTAINER_IMAGE_PATH: codefirst.iut.uca.fr/iut_inf63/2026_1a_g12_maui/2026_1a_g2_poulain_boudon/doxygen:main
      NAMESPACE_NAME: arpoulain
      NAMESPACE_TOKEN: $NAMESPACE_TOKEN
  needs:
    - push-doxygen-documentation